stages:
  prepare:
    cmd: python src/prepare.py
    deps:
      - src/prepare.py
      - data/raw
    params:
      - base.languages
      - prepare.raw_data_dir
      - prepare.output_dir
    outs:
      - data/manifests

  augment:
    cmd: python src/augment.py
    deps:
      - src/augment.py
      - data/manifests    
    params:
      - base.languages
      - augment.snr_levels
      - augment.seed
      - augment.input_manifest_dir
      - augment.output_manifest_dir
      - augment.output_audio_dir
    outs:
      - data/manifests_noisy 
      - data/audio_noisy     